var imgData = {
  1: [
    "images/captcha/puppies/1.jpg",
    "images/captcha/puppies/2.jpg",
    "images/captcha/puppies/3.jpg",
    "images/captcha/puppies/4.jpg",
    "images/captcha/puppies/5.jpg",
    "images/captcha/puppies/6.jpg",
    "images/captcha/puppies/7.jpg",
    "images/captcha/puppies/8.jpg",
    "images/captcha/puppies/9.jpg",
    "puppies",
  ],
  2: [
    "images/captcha/rhinos/1.jpg",
    "images/captcha/rhinos/2.jpg",
    "images/captcha/rhinos/3.jpg",
    "images/captcha/rhinos/4.jpg",
    "images/captcha/rhinos/5.jpg",
    "images/captcha/rhinos/6.jpg",
    "images/captcha/rhinos/7.jpg",
    "images/captcha/rhinos/8.jpg",
    "images/captcha/rhinos/9.jpg",
    "rhinos"
  ],
  3: [
    "images/captcha/hydrants/1.jpg",
    "images/captcha/hydrants/2.jpg",
    "images/captcha/hydrants/3.jpg",
    "images/captcha/hydrants/9.jpg",
    "images/captcha/hydrants/4.jpg",
    "images/captcha/hydrants/8.jpg",
    "images/captcha/hydrants/5.jpg",
    "images/captcha/hydrants/6.jpg",
    "images/captcha/hydrants/7.jpg",
    "fire hydrants"
  ],
  4: [
    "images/captcha/trains/1.jpg",
    "images/captcha/trains/2.jpg",
    "images/captcha/trains/3.jpg",
    "images/captcha/trains/9.jpg",
    "images/captcha/trains/4.jpg",
    "images/captcha/trains/8.jpg",
    "images/captcha/trains/5.jpg",
    "images/captcha/trains/6.jpg",
    "images/captcha/trains/7.jpg",
    "trains"
  ],
  5: [
    "images/captcha/trains/5.jpg",
    "images/captcha/trains/1.jpg",
    "images/captcha/trains/3.jpg",
    "images/captcha/trains/7.jpg",
    "images/captcha/trains/9.jpg",
    "images/captcha/trains/4.jpg",
    "images/captcha/trains/8.jpg",
    "images/captcha/trains/2.jpg",
    "images/captcha/trains/6.jpg",
    "boats"
  ],
  6: [
    "images/captcha/trains/2.jpg",
    "images/captcha/trains/6.jpg",
    "images/captcha/trains/7.jpg",
    "images/captcha/trains/3.jpg",
    "images/captcha/trains/9.jpg",
    "images/captcha/trains/4.jpg",
    "images/captcha/trains/8.jpg",
    "images/captcha/trains/5.jpg",
    "images/captcha/trains/1.jpg",
    "busses"
  ],
};
